# Generated by Django 4.2.3 on 2023-08-04 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='student',
            managers=[
            ],
        ),
    ]
