# Generated by Django 4.2.3 on 2023-08-04 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0002_alter_student_managers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='email',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='student',
            name='username',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
